export const COHORT = {
  state: 'active' as 'active' | 'early' | 'soldout',
  date: 'Aug 27, 2026',
  dateShort: 'Aug 27',
  day: 'Thursday',
  time: '7:30 PM IST / 10 AM US Eastern',
  seatsTotal: 20,
  seatsLeft: 2,
  prevCohortDate: 'Jul 23',
  studentsTotal: '250+',
  priceIndia: '₹4,999',
  priceIntl: '$129',
  originalPriceIndia: '₹9,999',
  originalPriceIntl: '$249',
  capstonePriceIndia: '₹1,000',
  capstonePriceIntl: '$49',
  priceTaglineIndia: "That's just ₹1250 per live session with your mentor",
  priceTaglineIntl: "That's just $32.25 per live session with your mentor",
  pricePerSessionIndia: '₹1,250',
  pricePerSessionIntl: '$32.25',
  formUrl: 'https://learn.approachable.dev/registration',

  priceIncreaseAt: '2026-08-25T23:59:59+05:30',
  priceIncreaseDateShort: 'Aug 25',
  priceIndiaLate: '₹4,999',
  priceIntlLate: '$129',
  priceTaglineIndiaLate: "That's just ₹1,250 per live session with your mentor",
  priceTaglineIntlLate: "That's just $32.25 per live session with your mentor",
  pricePerSessionIndiaLate: '₹1,250',
  pricePerSessionIntlLate: '$32.25',
};
