export const COHORT = {
  state: 'early' as 'active' | 'early' | 'soldout',
  date: 'Aug 27, 2026',
  dateShort: 'Aug 27',
  day: 'Thursday',
  time: '7:30 PM IST / 10 AM US Eastern',
  seatsTotal: 20,
  seatsLeft: 15,
  prevCohortDate: 'Jul 23',
  studentsTotal: '250+',
  priceIndia: '₹3,999',
  priceIntl: '$99',
  originalPriceIndia: '₹7,999',
  originalPriceIntl: '$199',
  capstonePriceIndia: '₹1,000',
  capstonePriceIntl: '$49',
  priceTaglineIndia: "That's just ₹999 per live session with your mentor",
  priceTaglineIntl: "That's just $24.99 per live session with your mentor",
  pricePerSessionIndia: '₹999',
  pricePerSessionIntl: '$24.99',
  formUrl: 'https://learn.approachable.dev/registration',

  priceIncreaseAt: '2026-08-20T23:59:59+05:30',
  priceIncreaseDateShort: 'Aug 20',
  priceIndiaLate: '₹4,499',
  priceIntlLate: '$129',
  priceTaglineIndiaLate: "That's just ₹1,124 per live session with your mentor",
  priceTaglineIntlLate: "That's just $32.25 per live session with your mentor",
  pricePerSessionIndiaLate: '₹1,124',
  pricePerSessionIntlLate: '$32.25',
};
