media: public/images/posts
content:
  - name: posts
    label: Blog Posts
    type: collection
    path: content/posts
    filename: "{primary}.md"
    format: yaml-frontmatter
    view:
      primary: title
      sort: date
      order: desc
    fields:
      - name: title
        type: string
        required: true
      - name: date
        type: date
        required: true
      - name: excerpt
        type: text
        required: true
      - name: coverImage
        type: image
      - name: body
        type: rich-text
        required: true
